### ISSUE TITLE
Need some introduction 

### ISSUE THREAD

**Issue by QYWT** [YoushaaMurhij/PCDet_Infernece#1]
Hello, guys.
I am a novice to ROS, and I want to deploy PVRCNN to ROS. Can you give me a little help about your code？
What can your code do？How should I use it？

**Comment by YoushaaMurhij** [comment]
My code is a template for inference using ROS-node you can edit to match your method. Pay attention, you need to use ros-msgs format in your code. I used my custom msgs and they are not available in the code. I suggest you to use [jsk msgs](https://github.com/jsk-ros-pkg/jsk_recognition)

**Comment by QYWT** [comment]
Thanks for your advice
